# Generated by Django 4.1.3 on 2023-03-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_followers',
            old_name='follower_id',
            new_name='follower_email',
        ),
        migrations.RenameField(
            model_name='user_followers',
            old_name='user_id',
            new_name='user_email',
        ),
    ]
